import type { Metadata } from "next";
import { AppRouterCacheProvider } from '@mui/material-nextjs/v15-appRouter'
import NavigationContainer from "@/components/NavigationContainer";
import ProblemSelector from "@/components/ProblemSelector";

import './globals.css'

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const problemGroups: Record<number, number[]> = {
  2024: [1, 2, 3, 4],
  2023: [1],
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-background text-white">
        <AppRouterCacheProvider>
          <NavigationContainer drawerContent={<ProblemSelector problemMap={problemGroups} />}>
            {children}
          </NavigationContainer>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
